version: 2

# 1. Define how to build the binary
builds:
  - id: kiart
    dir: cmd/kiart # Points to where your main.go is
    binary: kiart
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

# 2. Define how to package the binaries
archives:
  - format: tar.gz
    # Use zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

# 3. Generate SHA256 checksums
checksum:
  name_template: "checksums.txt"

# 4. Create the Homebrew Formula and push to your Tap!
brews:
  - name: kiart
    description: "A blazing fast CLI tool to convert images to high-res ASCII art."
    homepage: "https://github.com/nendix/kiart"

    repository:
      owner: nendix
      name: tap

    directory: Formula
