version: 2

project_name: kiart

before:
  hooks:
    - go mod tidy

builds:
  - id: kiart
    main: ./cmd/kiart
    binary: kiart
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"

release:
  github:
    owner: nendix
    name: kiart
  draft: false
  prerelease: auto

brews:
  - name: kiart
    description: "A blazing fast CLI tool to convert images to high-res ASCII art."
    homepage: "https://github.com/nendix/kiart"
    repository:
      owner: nendix
      name: tap
    directory: Formula
